name: check
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14]
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v12
        with:
          name: risc0pkgs
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: System Info
        run: |
          uname -a
          nix --version

      - name: format
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#checks.x86_64-linux.format

      - name: r0vm
        if: matrix.os == 'ubuntu-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-linux.r0vm

      - name: template
        if: matrix.os == 'ubuntu-latest'
        run: |
          git config --global init.defaultBranch main
          ./scripts/use-template.sh

      - name: r0vm
        if: matrix.os == 'macos-latest'
        run: nix build -L --no-link --show-trace .#packages.x86_64-darwin.r0vm

      - name: template
        if: matrix.os == 'macos-latest'
        run: |
          git config --global init.defaultBranch main
          ./scripts/use-template.sh

      - name: r0vm
        if: matrix.os == 'macos-14'
        run: nix build -L --no-link --show-trace .#packages.aarch64-darwin.r0vm

      - name: template
        if: matrix.os == 'macos-14'
        run: |
          git config --global init.defaultBranch main
          ./scripts/use-template.sh
